spring.application.name=tvmaze

spring.data.mongodb.uri=mongodb+srv://romeromaciasorlando_db_user:tQwJg9HE0dfyttfY@clustertvmaze.roo4uiy.mongodb.net/tvmaze_db?retryWrites=true&w=majority&appName=ClusterTVmaze